---
- name: "Manage User/Group permissions"
  gather_facts: false
  hosts: "ipa_servers"
  vars_files:
    - "../ipa_vars.yml"
  collections:
    - "freeipa.ansible_freeipa"
  tasks:
#
# Default groups
#
    - name: "Create group grp_soc_team"
      ipagroup:
        name: "grp_soc_team"
        ipaadmin_principal: "{{ ipaadmin_principal }}"
        ipaadmin_password: "{{ ipaadmin_password }}"

    - name: "Create group grp_dev_team"
      ipagroup:
        name: "grp_dev_team"
        ipaadmin_principal: "{{ ipaadmin_principal }}"
        ipaadmin_password: "{{ ipaadmin_password }}"

    - name: "Create group svc_psql_rw"
      ipagroup:
        name: "svc_psql_rw"
        ipaadmin_principal: "{{ ipaadmin_principal }}"
        ipaadmin_password: "{{ ipaadmin_password }}"

    - name: "Create group svc_psql_ro"
      ipagroup:
        name: "svc_psql_ro"
        ipaadmin_principal: "{{ ipaadmin_principal }}"
        ipaadmin_password: "{{ ipaadmin_password }}"
#
# Default users
#
    - name: "Create default users"
      ipauser:
        users:
          - name: "testing"
            first: "Test"
            last: "User"
            shell: "/bin/bash"

          - name: "test_user_01"
            first: "Test"
            last: "User"
            shell: "/bin/bash"

          - name: "test_user_02"
            first: "Test"
            last: "User"
            shell: "/bin/bash"

          - name: "test_user_03"
            first: "Test"
            last: "User"
            shell: "/bin/bash"

          - name: "test_user_04"
            first: "Test"
            last: "User"
            shell: "/bin/bash"
